name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.16.0

dependencies:
  flame: ^1.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  assets: 
    - assets/icons/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansText-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSansText-Regular.ttf
          weight: 400

flutter_gen:
  uses-material-design: true
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80  
